import { Link } from 'react-router-dom';
import { ArrowRight,ArrowUpRight,Heart,BriefcaseBusiness,Coins,Sun,Sparkles,ShieldCheck,Moon,Star } from 'lucide-react';
import { CardBack,CardImage } from '../components/Card';
import { tarotCards } from '../data/tarotCards';
import { spreads } from '../data/options';
const topics=[['love',Heart,'Tình yêu & kết nối','Lắng nghe những điều trái tim muốn nói.','rose'],['career',BriefcaseBusiness,'Công việc & hành trình','Tìm góc nhìn mới cho con đường của bạn.','teal'],['finance',Coins,'Tài chính & ổn định','Chiêm nghiệm về sự đủ đầy và cân bằng.','gold'],['daily',Sun,'Thông điệp hôm nay','Một lời nhắn nhỏ dành riêng cho ngày mới.','lavender']];
const faq=[['Tarot có chính xác không?','Tarot là công cụ biểu tượng để tự chiêm nghiệm, không có cơ sở khoa học để xác nhận khả năng dự đoán. Giá trị nằm ở những câu hỏi và góc nhìn mà bạn rút ra.'],['Tarot online có giống Tarot ngoài đời không?','Bạn vẫn chọn chủ đề, xào bộ 78 lá, tự chọn lá úp và đọc theo vị trí. Trải nghiệm online không thay thế cuộc trò chuyện trực tiếp với người đọc bài.'],['Lá ngược có nghĩa là xấu không?','Không. Lá ngược có thể gợi ý năng lượng hướng vào bên trong, sự trì hoãn, mất cân bằng hoặc một cách hiểu khác của chủ đề lá bài.'],['Có thể xem Tarot nhiều lần không?','Bạn có thể trải bài nhiều lần, nhưng nên dành thời gian suy ngẫm thay vì rút lại chỉ để tìm câu trả lời mong muốn. Tarot hôm nay giữ một lá trong ngày trên trình duyệt này.'],['Website có lưu câu hỏi của tôi không?','Câu hỏi và lịch sử được lưu trên thiết bị của bạn. Ở chế độ mặc định, nội dung trải bài không được gửi lên máy chủ. Bạn có thể xóa lịch sử bất cứ lúc nào.'],['Tarot có dự đoán chắc chắn tương lai không?','Không. Tương lai phụ thuộc nhiều yếu tố và lựa chọn của bạn; các lá bài chỉ gợi ý những chủ đề để cân nhắc.']];
export default function Home(){return <>
 <section className="hero"><div className="hero-stars" aria-hidden="true">✦<span>✧</span><i>✦</i></div><div className="hero-content"><div className="eyebrow"><span/> LẮNG NGHE TRỰC GIÁC CỦA BẠN <span/></div><div className="hero-brand">HOANPHAMTAROT</div><h1>Thông điệp nào<br/>đang <em>chờ bạn?</em></h1><p>Đặt câu hỏi, chọn những lá bài thu hút bạn nhất và<br className="desktop-break"/> khám phá thông điệp Tarot dành cho bạn.</p><div className="hero-actions"><Link className="button primary" to="/reading"><Sparkles size={17}/> Rút bài ngay <ArrowRight size={17}/></Link><Link className="button ghost" to="/reading">Rút bài & trò chuyện <ArrowUpRight size={17}/></Link></div><div className="hero-fan" aria-hidden="true">{[-2,-1,0,1,2].map((n)=><div className="hero-card" key={n} style={{'--n':n}}><CardBack/></div>)}</div></div><div className="hero-note"><span><Star size={13}/> 78 lá Rider-Waite-Smith</span><span><ShieldCheck size={13}/> Riêng tư & miễn phí</span><span><Moon size={13}/> Một khoảng lặng cho tâm hồn</span></div></section>
 <section className="section topics"><div className="section-heading"><div><div className="eyebrow">BẮT ĐẦU TỪ ĐIỀU BẠN QUAN TÂM</div><h2>Bạn đang tìm kiếm điều gì?</h2></div><Link className="text-link" to="/reading">Tất cả chủ đề <ArrowRight size={16}/></Link></div><div className="topic-grid">{topics.map(([url,Icon,title,description,color])=><Link to={`/${url}`} className={`topic ${color}`} key={url}><Icon size={27} strokeWidth={1.2}/><h3>{title}</h3><p>{description}</p><ArrowUpRight className="topic-arrow" size={18}/></Link>)}</div></section>
 <section className="section spread-section"><div className="section-heading"><div><div className="eyebrow">MỖI TRẢI BÀI, MỘT GÓC NHÌN</div><h2>Chọn cách bạn muốn lắng nghe</h2></div><span className="muted">Đi chậm một chút. Hiểu mình hơn một chút.</span></div><div className="spread-grid">{Object.entries(spreads).map(([id,s])=><Link className="spread-item" key={id} to={`/reading?spread=${id}`}><div className="mini-spread" aria-hidden="true">{s.positions.map((_,i)=><div key={i} style={{transform:`rotate(${(i-(s.positions.length-1)/2)*8}deg)`}}><Moon size={16}/></div>)}</div><span className="eyebrow">{s.positions.length} LÁ {id==='yes-no'?' · YES / NO':''}</span><h3>{s.name}</h3><p>{s.description}</p><ArrowRight size={18}/></Link>)}</div></section>
 <section className="daily-band"><Sun size={58} strokeWidth={0.8}/><div><div className="eyebrow">MỖI NGÀY LÀ MỘT KHỞI ĐẦU</div><h2>Một lá bài cho hôm nay</h2><p>Dành một phút để dừng lại, hít thở và đón nhận một góc nhìn mới.</p></div><Link className="button primary" to="/daily">Nhận thông điệp <ArrowRight size={17}/></Link></section>
 <section className="section"><div className="section-heading"><div><div className="eyebrow">NHỮNG BIỂU TƯỢNG BIẾT KỂ CHUYỆN</div><h2>Gặp gỡ những lá bài</h2></div><Link className="text-link" to="/cards">Khám phá bộ bài <ArrowRight size={16}/></Link></div><div className="featured-grid">{[17,2,6,19].map(i=><Link to={`/cards/${tarotCards[i].slug}`} key={i} className="featured-card"><CardImage card={tarotCards[i]}/><span className="eyebrow">MAJOR ARCANA · {String(i).padStart(2,'0')}</span><h3>{tarotCards[i].name}</h3><p>{tarotCards[i].vietnameseName}</p></Link>)}</div></section>
 <section className="section about"><Sparkles size={32} strokeWidth={1}/><div className="eyebrow">KHÔNG GIAN DÀNH CHO SỰ CHIÊM NGHIỆM</div><h2>Đôi khi, câu trả lời bắt đầu<br/>từ một câu hỏi dành cho chính mình.</h2><p>78 lá bài là 78 câu chuyện về những trải nghiệm rất con người: khởi đầu, kết nối, đổi thay và trưởng thành. HoanPhamTarot mời bạn nhìn những câu chuyện ấy như một tấm gương để hiểu mình, với sự cởi mở và quyền tự quyết luôn thuộc về bạn.</p></section>
 <section className="section faq"><div><div className="eyebrow">MỘT CHÚT RÕ RÀNG</div><h2>Có thể bạn đang tự hỏi</h2></div><div>{faq.map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 </>;}
